import type { Metadata } from "next";
import "../styles/global.scss";
import { firacode, inter } from "@/lib/fonts";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.variable,
          firacode.variable,
          "font-firacode no-scrollbar",
          "bg-vista-white dark:bg-gunmetal"
        )}
      >
        {children}
      </body>
    </html>
  );
}
